2021/10/12 02:12:36 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/10/12 02:12:37 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/favicon.ico" (from "http://localhost/")" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/12 02:15:09 [error] 31#31: *5 FastCGI sent in stderr: "PHP message: 2021-10-12T02:15:09+00:00 [critical] Uncaught Error: syntax error, unexpected identifier "extend", expecting "{"" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/10/13 01:31:51 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/10/13 01:31:51 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/favicon.ico" (from "http://localhost/")" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/13 02:19:45 [error] 32#32: *5 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/10/13 03:40:23 [error] 32#32: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/13 04:13:55 [error] 32#32: *5 FastCGI sent in stderr: "PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136
PHP message: [debug] Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::logKernelException".
PHP message: [debug] Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelException".
PHP message: [debug] Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelException".
PHP message: [debug] Listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelException" stopped propagation of the event "kernel.exception".
PHP message: [debug] Listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onKernelException" was not called for event "kernel.exception".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDat
2021/10/13 04:13:56 [error] 32#32: *5 FastCGI sent in stderr: "PHP message: [info] Matched route "_wdt".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleAwareListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
PHP message: [debug] Notified event "kernel.controller_arguments" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onControllerArguments".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelResponse".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse".
PHP mes
2021/10/25 02:45:05 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CCommentCrudController&menuIndex=2&signature=X74VTtbn0xLlzFxzyEREmT1lpprJncw63PAsbLUCuYo&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CConferenceCrudController&signature=0n11PmVegYwvxmfY2aYILYHCXL01QJOxgn2usjOwbqc"
2021/10/25 02:45:05 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CCommentCrudController&menuIndex=2&signature=X74VTtbn0xLlzFxzyEREmT1lpprJncw63PAsbLUCuYo&submenuIndex=-1"
2021/10/25 02:45:12 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:45:12 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:14 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:14 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:14 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:14 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:31 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:31 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/25 02:46:37 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:37 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/25 02:46:40 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:41 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/25 02:46:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/25 02:46:54 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:54 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/25 02:47:17 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:47:17 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/25 02:47:17 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:47:17 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/25 02:47:18 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:47:18 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/31 20:24:12 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CConferenceCrudController&signature=0n11PmVegYwvxmfY2aYILYHCXL01QJOxgn2usjOwbqc HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/31 20:24:12 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CConferenceCrudController&signature=0n11PmVegYwvxmfY2aYILYHCXL01QJOxgn2usjOwbqc"
2021/10/31 20:24:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/31 20:24:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/31 20:24:50 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/31 20:24:50 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/31 20:24:55 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/31 20:24:56 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/index.php"
2021/11/01 16:13:23 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:23 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:26 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:26 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:50 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:50 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:51 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:51 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/11 23:19:18 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/11 23:19:18 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/11 23:19:21 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/11 23:19:21 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/12 06:23:24 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Sign_up HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/12 06:23:24 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/12 06:23:27 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Sign_up HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/12 06:23:28 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/14 15:55:52 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:55:53 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:29 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:30 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:31 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:31 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:34 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:57:05 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:57:06 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:57:06 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:57:07 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 18:18:04 [error] 32#32: *119 FastCGI sent in stderr: "PHP message: 2021-11-14T18:18:04+00:00 [critical] Uncaught Exception: The child config "authorization_server" under "league_oauth2_server" must be configured" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:41:36 [error] 33#33: *133 FastCGI sent in stderr: "PHP message: 2021-11-15T06:41:36+00:00 [critical] Uncaught Exception: Case mismatch between loaded and declared class names: "App\utils\MomentFormatConverter" vs "App\Utils\MomentFormatConverter" in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:46:51 [error] 32#32: *136 FastCGI sent in stderr: "PHP message: 2021-11-15T06:46:51+00:00 [critical] Uncaught Exception: Case mismatch between loaded and declared class names: "App\utils\Validator" vs "App\Utils\Validator" in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:51:18 [error] 32#32: *139 FastCGI sent in stderr: "PHP message: 2021-11-15T06:51:18+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$validator" of method "__construct()" references class "App\Utils\Validator" but no such service exists. Did you mean "App\utils\Validator"?" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:51:27 [error] 32#32: *139 FastCGI sent in stderr: "PHP message: 2021-11-15T06:51:27+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$validator" of method "__construct()" references class "App\Utils\Validator" but no such service exists. Did you mean "App\utils\Validator"?" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:53:07 [error] 32#32: *143 FastCGI sent in stderr: "PHP message: 2021-11-15T06:53:07+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\ListUsersCommand": argument "$emailSender" of method "__construct()" is type-hinted "string", you should configure its value explicitly" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:56:01 [error] 32#32: *147 FastCGI sent in stderr: "PHP message: 2021-11-15T06:56:01+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\ListUsersCommand": argument "$emailSender" of method "__construct()" is type-hinted "string", you should configure its value explicitly" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:58:31 [error] 33#33: *149 FastCGI sent in stderr: "PHP message: 2021-11-15T06:58:31+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\ListUsersCommand": argument "$emailSender" of method "__construct()" is type-hinted "string", you should configure its value explicitly" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 07:00:00 [error] 32#32: *153 FastCGI sent in stderr: "PHP message: 2021-11-15T07:00:00+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\ListUsersCommand": argument "$emailSender" of method "__construct()" is type-hinted "string", you should configure its value explicitly" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
